import {
	writeFileSync,
	readdirSync
} from 'fs';

import path from 'path';

const APP_DIR = 'app';
const LISTING_FILE = 'listing.GENERATED.ts';
//TODO: this must be a constant somewhere else, right?
const SEEDS_DIRECTORY = 'seeds';

const generateListing = () => {
	const datafiles = [];
	for (const file of readdirSync(SEEDS_DIRECTORY)) {
		if (!file.endsWith('.json')) continue;
		datafiles.push(file);
	}
	const data =`//This file was generated by 'npm run generate:config'

import {
	z
} from 'zod';

export const knownSeedFiles = z.enum([
	${datafiles.map(filename => `'${filename}'`).join(',\n\t')}
]);

export type KnownSeedFiles = z.infer<typeof knownSeedFiles>;
`;

	return data;
};

const writeConfig = () => {
	const data = generateListing();
	const file = path.join(APP_DIR, LISTING_FILE);
	writeFileSync(file, data);
};

const main = () => {
	writeConfig();
};

(() => {
	main();
})();